import Head from 'next/head'
import {BsFillMoonStarsFill, BsLinkedin, BsInstagram, BsGithub} from 'react-icons/bs';
import Image from "next/image"
import nimImg from "../public/IMG-0546.jpg"
import design from "../public/design.png"
import consulting from "../public/consulting.png"
import dode from "../public/code.png"
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Nimalan Karthik Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        {/* Section 1 - Intro */}

        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl pl-5 font-burtons  '>NKR</h1>
            <ul className='flex items-center pr-5'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointers text-2xl'/>
              </li>
              <li>
                <a onClick={(e) => {
                    e.preventDefault();
                    window.location.href='https://drive.google.com/file/d/1bwIunbGm0PDIKmx9X1n14fOOptc-3rqa/view?usp=sharing';
                  }} 
                className='bg-gradient-to-r from-cyan-500 to-blue-900 text-white px-4 py-2  rounded-md ml-8' href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className='px-5'>
            <h2 className='text-4xl font-semibold text-blue-900  text-center'>Nimalan Karthik Rajasekar</h2>
            <h3 className='text-2xl font-normal  text-center'>Developer</h3>
            <br></br>
            <p className='font-light py-3 flex-wrap justify-center text-center'>
            Master’s in Computer Science student at UC Riverside with demonstrated experience in building and
            maintaining production-ready web applications. With 2 years of full-time software development
            experience at SAP Labs and 6 months of software development internship experience at Healthedge, looking forward to assist the
            hiring team at GM in designing, developing and maintaining the product as an Software Engineering Intern.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-5 text-gray-700'>
            <BsLinkedin  onClick={(e) => {
                    e.preventDefault();
                    window.location.href='https://www.linkedin.com/in/nimalan-karthik/';
                  }}></BsLinkedin>
            <BsGithub  onClick={(e) => {
                    e.preventDefault();
                    window.location.href='https://github.com/nimalankarthik';
                  }}></BsGithub>
            <BsInstagram onClick={(e) => {
                    e.preventDefault();
                    window.location.href='https://www.instagram.com/nimalan.karthik/';
                  }}></BsInstagram>
           </div>
           <div className='relative mx-auto rounded-full h-80 w-80 mt-10 overflow-hidden'>
            <Image alt='DP' src={nimImg}>
            </Image>
            <br></br>
           </div>
        </section>

        <hr className='text-black '></hr>

        {/* Section 2 - Projects */}
        <br></br>
      <section className='px-5' >
        <h2 className='text-4xl font-semibold text-blue-900  text-center'>Projects</h2>
        <div className='flex items-center justify-center'>

          <div className='"flex text-center items-center justify-center shadow-lg p-10 rounded-xl my-10 '> 
            <h3 className='text-lg font-medium align-middle pt-8 pd-2'>project 1</h3>
            <Image alt="icon1" src={design} width={200} height={200}></Image>    
            <p>Hello This is my Project number 1</p>
          </div>

          <div className='"flex text-center items-center justify-center shadow-lg p-10 rounded-xl my-10 '>
            <h3 className='text-lg font-medium align-middle pt-8 pd-2'>project 2</h3>
            <Image alt="icon1" src={consulting} width={200} height={200}></Image>    
            <p>Hello This is my Project number 2</p>
          </div>

          <div className='"flex text-center items-center justify-center shadow-lg p-10 rounded-xl my-10 '>
            <h3 className='text-lg font-medium align-middle pt-8 pd-2'>project 3</h3>
            <Image alt="icon1" src={dode} width={200} height={200}></Image>    
            <p>Hello This is my Project number 3</p>
          </div>
        </div>
      </section>

      <hr className='text-black '></hr>

      {/* Section 3 - Skills and Education */}
      <section>
      <div className="grid grid-cols-2 gap-4">
      <div className='text-4xl font-semibold text-blue-900  text-center'>Skills
      <div className='text-base font-semibold text-black'>
        <ul >
          <li className='px-5 py-5 shadow-2xl'>Python</li>
          <li className='px-5 py-5 shadow-2xl'>Javascript</li>
          <li className='px-5 py-5 shadow-2xl'>HTML/CSS</li>
        </ul> 
      </div>
      </div>
      <div className='text-4xl font-semibold text-blue-900  text-center'>Education
      <div className='text-base font-semibold text-black'>
        <ul>
          <li className='px-5 py-5 shadow-2xl'>
            <h2>University of California Riverside</h2>
            <h3 className='font-light'>Master of Science in Computer Science</h3>
            </li>
          <li className='px-5 py-5 shadow-2xl'>
          <h2>Amrita Vishwavidyapeetham University</h2>
            <h3 className='font-light'>Bachelor of Technology in Computer Science & Engineering</h3>
          </li>
        </ul> 
      </div>
      </div>
      </div>  
      </section>

      </main>
    </div>
  );
}
